name: Realm test


on:
        push:
                branches:
                - main


jobs:
        edit-test:
                name: test


                runs-on: ubuntu-latest
                steps:
                - uses: actions/checkout@v2

                - name: "time variable"
                  run: echo "CURRENT_TIME=$(date +'%Y-%m-%d_%s')" >> $GITHUB_ENV


                - name: "master branch"
                  if: ${{ github.ref == 'refs/heads/main'  }}
                  run: |
                       echo "REALM_APP_ID=application-1-wasyt" >> $GITHUB_ENV
                       cd environments
                       printf '{\n      "values": {"databaseName": "Cluster0"}\n}' > development.json
                       cd ..
                       sed -i 's/{/{ "environment": "development",/' realm_config.json 

                - name: "Auth"
                  run: |
                       npm install -g mongodb-realm-cli@beta
                       realm-cli login --api-key="${{ secrets.REALM_API_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_API_PRIVATE_KEY }}" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com


                - name: "Push"
                  if: ${{ env.REALM_APP_ID }}
                  run: |
                       cd environments
                       realm-cli push --remote="${{ env.REALM_APP_ID }}" -y

                  
